### ISSUE TITLE
Graph Shrinking

### ISSUE THREAD

**Issue by XFrozenSoilX** [elxris/Turnip-Calculator#64]
Using Microsoft Edge browser, the graph is shrinking vertically until it disappears. Using the inspector I can see the heights in this code starts around 566 and 400px and increments down to 0 in a matter of seconds.

<canvas unselectable="on" width="1276" **height="0**" style="user-select: none; display: block; box-sizing: border-box; width: 880px; **height: 0px**;"></canvas>

Forcing the second (px) value to anything over 641px has it shrink to 641px. Setting it to 1600px shrinks it down to 1282px (excactly 2x 641px).

Works fine in Chrome and Firefox. Worked fine in Edge until recently.

**Comment by elxris** [comment]
Hi @XFrozenSoilX!

I could not reproduce what you said.
Can you verify your browser is Edge 80 (latest) and on the bottom of the page is the latest version of the calculator (v1.8-alpha)?

**Comment by Jeryes** [comment]
Also happening to me on my Pixel 2 in Google Chrome.

**Comment by TheJadeKitten** [comment]
Mine is doing this too! It just starts shrinking until it's gone. It was fine yesterday. I'm using Chrome for Android.

**Comment by elxris** [comment]
Thank you a lot for the heads up!

Can you confirm it's fixed in "v1.8-beta.a"?

**Comment by TheJadeKitten** [comment]
> Thank you a lot for the heads up!
> 
> Can you confirm it's fixed in "v1.8-beta.a"?

My version says "v1.8-alpha" and it is still occurring. Is there a way I can get to v1.8-beta.a to test?

**Comment by elxris** [comment]
I use a hard reload (windows ctrl+shift+r or mac cmd+shift+r) on Firefox, don't know if it works on Chrome.

**Comment by TheJadeKitten** [comment]
> Mine is doing this too! It just starts shrinking until it's gone. It was fine yesterday. I'm using Chrome for Android.

This issue has been resolved for me, as of today. I'll let you know if I see it again. Thanks!

**Comment by elxris** [comment]
I will close this. Feel free to open another issue if this is not resolved!
